### PR TITLE
Include issues from github private repos. Fix #282

### LINKED ISSUE #282: Private github tasks are not pulled
I've create a token with `repo`, Full control of private repositories, scope. When I access the github API using `curl` I get what I expect, the issues for the private repo I retrieved.

I used that: `curl -u fifigyuri:<token> https://api.github.com/repos/netronixgroup/environet-ui/issues`

And I've got the list of private repo's issues. But bugwarrior does not load these issues for me. This is my config file:

```
[general]
targets = netronix_github
taskrc = ~/.taskrc
shorten = True
annotation_links = True

[netronix_github]
service = github
project_template = {{project|lower}}
description_template = {{githubnumber}}: {{githubtitle}}
github.username = netronixgroup
github.login = fifigyuri
github.token = <token>
github.import_labels_as_tags = True
github.label_template = gh-{{label}}
github.filter_pull_requests = True
```

The public issues I have are pulled, but I'd like to see the private ones only. What went wrong? Where did I make a mistake? Thank you for your help!

### PR DESCRIPTION
**Pull request by ryneeverett**
It seems that the distinction was not properly documented for some time,
but it now is. `/user/repos` includes all repos the authorized user has
access to, but `/users/:username/repos` only includes public repos.
http://stackoverflow.com/questions/21907278/github-api-using-repo-scope-but-still-cant-see-private-repos

### CODE REVIEW

**Comment by gdetrez** [comment]
I'm not sure I understand it correctly but it seems that the way `public_only` is set will prevent you from getting issues from a private repositories belonging to an other user or an organization.

Now that I think about it, it seems that there is actually no way to make sure we include all the repositories without systematically requesting both `/user/repos` and `/user/:username/repos`.

**Comment by ryneeverett** [comment]
@gdetrez You're right. I actually realized this back when I was triaging #282 but I couldn't understand my own comment just a minute ago:

>  I think the solution would be to make a call to https://api.github.com/user/repos and then filter out the ones that aren't owned by a github.username.

**Comment by ryneeverett** [comment]
Closing as there's basically nothing right about this.

**Comment by ryneeverett** [comment]
> Now that I think about it, it seems that there is actually no way to make sure we include all the repositories without systematically requesting both /user/repos and /user/:username/repos.

Why would we still need to call /user/:username/repos? User-owned issues should be included in /user/repos.

**Comment by gdetrez** [comment]
> Why would we still need to call /user/:username/repos? User-owned issues should be included in /user/repos.

If one wants to track issues from a (public) repository they are not a member of.

**Comment by ryneeverett** [comment]
Oh, got it.

**Pull request closed without merging**
