### PR TITLE
redmine: import first 100 issues instead 25

### PR DESCRIPTION
**Pull request by lzap**
This is quick and dirty patch to increase current limitation from 25 records
returned to 100 (hard coded maximum). Fore more, we'd need to implement
pagination. Since I have less then 100 bugs assigned, I am not interested in
that for the moment. But who knows :-)

### CODE REVIEW

**Comment by lzap** [comment]
For the record, the relevant page you are looking for is at http://www.redmine.org/projects/redmine/wiki/Rest_api

**Comment by beav** [comment]
I have less than 25 issues, but this patch did not break anything when I applied it and ran a pull.

**Comment by kostajh** [comment]
@lzap @beav please also have a look at my PR for #395 which includes this. Thanks!

**Comment by lzap** [comment]
Thanks for the test fix!

**Pull request merged**
