### PR TITLE
Use setuptools entry points instead of DeferredImport

### PR DESCRIPTION
**Pull request by puiterwijk**
This way, it is possible to use services implemented in external
packages

Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by coddingtonbear** [comment]
Ahh, @puiterwijk, @ralphbean & I had discussed making this kind of change a year or so ago, but there were some reservations (which may by this point not be great) raised.  @ralphbean what do you think?

**Comment by ralphbean** [comment]
No, I don't remember the points in our original discussion @coddingtonbear.  I'll try to have a look at this soon!

**Comment by coddingtonbear** [comment]
If it helps, and if you log our conversations on Freenode, it was there -- search for "entrypoint" or something like that.  I *think* I may have been using my former office's computer at the time, so I'm not sure I still have the transcripts.

**Comment by ralphbean** [comment]
Unfortunately I don't still have those logs.

Anyways, the code change looks fine to me.  And I suppose it would be nice to allow external plugins.

Let's let it sit a few more days, but I'm inclined to approve and merge this unless you have any objections @coddingtonbear.

**Comment by puiterwijk** [comment]
Pull request rebased.

**Comment by ralphbean** [comment]
:+1:.  Thanks Patrick!  :)  Happy plugin-writing!

**Comment by puiterwijk** [comment]
Thank you very much!

**Pull request merged**
