### PR TITLE
set allow_no_value=True so that it doesn't break on Python 3.7

### PR DESCRIPTION
**Pull request by archite**
Resolves the issue where one gets the error "configparser: TypeError: option values must be strings" as in #597.

### CODE REVIEW

**Comment by wookietreiber** [comment]
Please also add Python 3.7 to travis, so this is properly checked.

**Comment by wookietreiber** [comment]
My bad, seems travis does not yet support Python 3.7 :(

The other travis errors seem to be sporadic `apt` issues. I guess, we can either restart or ignore these.

**Comment by archite** [comment]
I assumed it might have had it. I’m not much for Travis as I use GitLab for work and personal.

**Comment by ryneeverett** [comment]
Merged da9221ea673b32fe3f9732b13c818604cf657230.

**Pull request closed without merging**
