### PR TITLE
[WIP] Add support for Kanboard service (fixes: #223)

### PR DESCRIPTION
**Pull request by nblock**
- [x] Add `kanboard` service
- [ ] Support for common service features
- [ ] Unit tests
- [x] Add documentation
- [X] Update README

### CODE REVIEW

**Comment by ralphbean** [comment]
Before you finish here, @nblock - may I ask if you are willing to help support the `kanboard` module in the future?  I don't have a kanboard account or use for it... so I'll have  lot of trouble triaging incoming bugs.

**Comment by nblock** [comment]
I'm involved in projects where Kanboard is used for planning and I'm willing to support this contribution. I can't guarantee support forever, but I'm willing to help.

**Comment by ralphbean** [comment]
> I can't guarantee support forever, but I'm willing to help.

Same here.  :)

**Comment by ralphbean** [comment]
Note to self (I'm combing through the PR queue) this one is close to ready.

@nblock have you had a chance to work on it?  I hope #663 isn't driving you crazy.  :)

**Comment by nblock** [comment]
@ralphbean I'm using it on a daily basis, but I don't find the time to complete it in the near future. I'll just close it for now, so you don't have to bother with it. Once I find the time, I'll continue working on it and rebase against the current master.

**Comment by ralphbean** [comment]
Sounds good.  Thanks @nblock!

**Pull request closed without merging**
