### PR TITLE
Fix #254 "Edit on Github" documentation links.

### LINKED ISSUE #254: Broken "Edit on GitHub" links on readthedocs.org
When you click on the link, you get a 404 page on github.

I think this is due to the fact that docs/source is a symbolic link.

### PR DESCRIPTION
**Pull request by ryneeverett**
From [the RTD
docs](https://read-the-docs.readthedocs.org/en/latest/builds.html#sphinx):

> When you choose Sphinx as your Documentation Type...We will look inside
> a doc or docs directory first, and then look within your entire project.

My interpretation is that removing the /docs directory from the project
root will cause RTD to search the entire project and find the nested
directory.

### CODE REVIEW

**Comment by ryneeverett** [comment]
To be clear: I don't really know if this will work.

**Comment by ralphbean** [comment]
Cool.  Let's see!

**Comment by ryneeverett** [comment]
Woohoo! Vague documentation correctly interpreted!

**Comment by ralphbean** [comment]
:tada:

**Pull request merged**
