### PR TITLE
Escaping fixes + only_on_new_tasks notifications + jira estimate

### PR DESCRIPTION
**Pull request by devenv**
As it cuts the description after some characters  there is sometimes an unmatched bracket
e.g. from jira: "Some bug (only in dev..."
TaskWarrior kinda freaks out at this...

### CODE REVIEW

**Comment by devenv** [comment]
Added an option not to fire a notification when pulled via cron and nothing new received...

**Comment by devenv** [comment]
+ in the description triggers task update...
May be these escaping issues should be tested in TW...

**Comment by devenv** [comment]
Added jira estimate UDA

**Comment by ralphbean** [comment]
Thanks for the patches @devenv, but I'm going to close this PR without merging.  Some of the changes need to be submitted to other libraries, other changes need explanation, etc..

**Pull request closed without merging**
