### PR TITLE
WIP: bitbucket: support teams

### PR DESCRIPTION
**Pull request by mathstuf**
---
Work in progress. Seems the API is a bit finicky when it comes to teams.

### CODE REVIEW

**Comment by ralphbean** [comment]
@mathstuf, just checking in.   Any updates on this?

**Comment by mathstuf** [comment]
No, I haven't worked on this in a while now. I will probably be doing work on some bitbucket repos next week, so between builds, maybe I can work on this some more.

**Comment by ralphbean** [comment]
Cool, cool.  No rush at all.

**Comment by ralphbean** [comment]
Any luck @mathstuf?

**Comment by ryneeverett** [comment]
If the problem was that there is no documented API, there's some ongoing discussion of it [here](https://bitbucket.org/site/master/issues/2323/create-a-way-to-group-repositories). As of yesterday, somebody seems to have found an internal API:

> For read access to the list of projects, I do see the (not yet public) API call to https://bitbucket.org/!api/internal/teams/<my-team>/projects/, so perhaps it will make its way to the public API eventually.

I expect bitbucket will respond within the next couple days.

**Comment by ralphbean** [comment]
OK, I'm going to close this one for now due to inactivity.  If there's renewed interest, feel free to re-open or re-file.

**Comment by mathstuf** [comment]
Seems Bitbucket finally [documented things](https://confluence.atlassian.com/bitbucket/teams-endpoint-423626335.html#teamsEndpoint-GETtheteam'srepositories). I'll see about trying and resurrecting this some time this month.

**Pull request closed without merging**
