### PR TITLE
JIRA:  Replace special reserved character, per JIRA API advice.

### LINKED ISSUE #644: The character '@' is a reserved JQL character
Based on the discussion [here](https://community.atlassian.com/t5/Jira-questions/JIRA-Rest-API-authentication-always-returns-401-unauthorized/qaq-p/187181), it seems that JIRA cloud usernames are now your login email address. What this means is that bugwarrior is generating JQL queries that contain the `@` symbol, and thus fails. The error log I'm getting in this situation is this (I've removed lines that mention my email address and login token, in case you're wondering why some lines are missing):
```
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [genovic_jira]
	text: Error in the JQL Query: The character '@' is a reserved JQL character. You must enclose it in a string or use the escape '\u0040' instead. (line 1, character 24)
	response text = {"errorMessages":["Error in the JQL Query: The character '@' is a reserved JQL character. You must enclose it in a string or use the escape '\\u0040' instead. (line 1, character 24)"],"errors":{}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/services/__init__.py", line 494, in _aggregate_issues
    for issue in service.issues():
  File "/usr/local/lib/python3.6/dist-packages/bugwarrior/services/jira.py", line 310, in issues
    cases = self.jira.search_issues(self.query, maxResults=-1)
  File "/usr/local/lib/python3.6/dist-packages/jira/client.py", line 2109, in search_issues
    issues = self._fetch_pages(Issue, 'issues', 'search', startAt, maxResults, search_params)
  File "/usr/local/lib/python3.6/dist-packages/jira/client.py", line 575, in _fetch_pages
    resource = self._get_json(request_path, params=page_params, base=base)
  File "/usr/local/lib/python3.6/dist-packages/jira/client.py", line 2549, in _get_json
    r = self._session.get(url, params=params)
  File "/usr/local/lib/python3.6/dist-packages/jira/resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jira/resilientsession.py", line 147, in __verb
    raise_on_error(response, verb=verb, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jira/resilientsession.py", line 57, in raise_on_error
    r.status_code, error, r.url, request=request, response=r, **kwargs)
```

### PR DESCRIPTION
**Pull request by ralphbean**
@TMiguelT, can you verify if this fixes #644?

### CODE REVIEW

**Comment by TMiguelT** [comment]
Hmm, no I'm still getting the error:
```
	text: Error in the JQL Query: The character '@' is a reserved JQL character. You must enclose it in a string or use the escape '\u0040' instead. (line 1, character 24)
```
This is after I ran `pip install git+https://github.com/ralphbean/bugwarrior.git@jira-reserved-at`.

**Comment by ralphbean** [comment]
Weird.  See that I'm logging the JQL query now in there?  Can you look at that and see if it makes sense?

**Comment by TMiguelT** [comment]
Oh haha I worked it out. What you're doing at the moment is replacing `@` with `@`, because Python intercepts the `\u` escape code and converts it to `@` internally. If you don't want python to do that, you'd need to do something like `\\u0040`.

However, I've read some of the JQL documentation, and I think it would be neater to use their recommended character escape for [reserved characters](https://confluence.atlassian.com/jiracoreserver073/advanced-searching-861257209.html#Advancedsearching-restrictions), which is two backslashes.

I think it would be something like:
```python
def jira_escape(s):
    return re.sub('[ +.,;?|*/%^$#@[\]]', r'\\\1'):
```

> Weird. See that I'm logging the JQL query now in there? Can you look at that and see if it makes sense?

No, I wasn't able to see any logging at any point. But I guess that's something to do with how you have logging configured. Is there a way to decrease the log level from the CLI?

**Comment by ralphbean** [comment]
Nice.  :)

OK - updated the patch again.  Try that?

**Comment by TMiguelT** [comment]
Alas, I'm getting a different error:
```
text: Error in the JQL Query: '\.' is an illegal JQL escape sequence. The valid escape sequences are \', \", \t, \n, \r, \\, '\ ' and \uXXXX. (line 1, character 17)
```

However, I think I misread the docs. What it says is:

> If you wish to use these characters in queries, you need to:
> * surround them with quote-marks (you can use either single quote-marks (') or double quote-marks ("));
and, if you are searching a text field and the character is on the list of reserved characters for text searches,
> * precede them with two backslashes.

So we only backslash escape `+ - & | ! ( ) { } [ ] ^ ~ * ? \ :`, but we should *always* quote the input parameters.

If you give me write access to that branch I'm happy to fix up this PR for you.

**Comment by ralphbean** [comment]
Hey, I'm not sure how to give you access to just that branch.  Let's close this.  Can you pull the branch and open a new PR under your control?  Thanks in advance!

**Pull request closed without merging**
