### PR TITLE
Add an FAQ

### PR DESCRIPTION
**Pull request by gdetrez**
There are regularly new requests to support other ITS (#87, #204, #311, #356, #388, #400, #409...) so I tried to compile old answer to such issues and put the result in a new FAQ in the docs.

### CODE REVIEW

**Comment by ryneeverett** [comment]
What if we listed all the unimplemented services we need people to contribute in this FAQ section, and closed all those issues? When new issues like this are opened, we close them and add them to the list.

**Comment by ryneeverett** [comment]
Or say something like "If you think a service is missing from this list, please open a pull request adding it."

**Comment by gdetrez** [comment]
@ryneeverett I would rather keep the issues as they contain more metadata (who created it, when...), they provide an easy way to contact the person who requested the backend (for testing, contribution or just to know if it is still something they would want to use) and they provide a place for discussion.

On the other hand, I think it would be resonable to have a policy that such issue will be closed after X amount of time without activity.

**Comment by gdetrez** [comment]
If I understand correctly, you want to keep a list, outside of the issue tracker, of all backends that have been requested by someone but not implemented? What would that be for?

**Comment by ryneeverett** [comment]
There are two problems I'd like to see addressed: clutter in the issue tracker and clarity to potential contributors. I don't care what approach we take to addressing them.

**clutter**
To me, new service requests aren't really actionable tickets in the same sense that smaller feature or bug reports are. Implementing a new service is a pretty big job and it will get done when somebody wants it done enough to do it themselves. The only thing we need to discuss in the issue tracker is whether or not we will maintain support for the service. Usually this is pretty obvious, but there's also a huge grey area that we haven't really gotten into yet (#297, #398). It seems like the proportion of issues that are just "implement this new service" has been growing, which is presumably the catalyst of this PR.

**clarity**
If we're going to close some of the old issues, we should be unambiguous about whether we would maintain support for the service should someone contribute it. Closed issues are often interpreted as "wontfix". One approach would be a canned response ("Closing for inactivity, but we'd happily merge a PR...") but I'm not sure we can count on people actually reading the bottom comment. I would suggest that we could make ourselves perfectly clear and solicit new contributors by giving a similar level of visibility to "Services you can Contribute" as "Supported Services".

**Comment by ryneeverett** [comment]
I'm going to go ahead and merge this, but I'd suggest you open an RFC so the team can hash out a policy before closing issues for "inactivity".

**Comment by gdetrez** [comment]
Thanks for merging @ryneeverett.

I don't plan on closing issues for inactivity. I personally don't mind those issues actually, I was only suggesting it as an alternative way to clear the issue tracker from less-actionable items.

**Comment by ryneeverett** [comment]
I think we're basically on the same page here -- "inactivity" isn't really a property of actionable tickets. If we had a mailing list, that would be a more appropriate place to discuss service requests. Adding them to a list is a hack to make unactionable items actionable.

**Pull request merged**
