### PR TITLE
Fix GitHub oracle in python3.

### PR DESCRIPTION
**Pull request by ryneeverett**
Based off #416.

### CODE REVIEW

**Comment by gdetrez** [comment]
This doesn't not work: if the token is `b"foobar"` the generated header value will be `token b'foobar'` (should be `token foobar`).

I would also suggest to move the fix "upstream": this might be an issue in other services so it might be safer to make sure that the oracle returns a `str` rather than making an conversion in the github service. It might be good to make the conversion explicit and make sure that it supports non ascii characters. (using system locale?)

It seem that this is based on a PR that wasn't merged, maybe rebase on develop for a cleaner pull request?

**Comment by ryneeverett** [comment]
Rebased.

**Comment by ryneeverett** [comment]
Oh, I see what you're saying.

```py
>>> 'token {token}'.format(token=b'token')
"token b'token'"
```

Hmm.

**Comment by ryneeverett** [comment]
I guess that error message wasn't joking: You really "Can't convert 'bytes' object to str implicitly".

**Comment by gdetrez** [comment]
What about moving the conversion to the oracle?

**Comment by gdetrez** [comment]
Also, the included test is not very useful, as demonstrated by the initial version of the PR ;-)
It should probably check the value of the 'Authorization' header

**Comment by ryneeverett** [comment]
Whoops, I overlooked that part of your comment. Agreed on both points, which leaves pretty much nothing of value here. I may not get back to this for a while so it might make sense to open an issue if you don't plan to tackle this yourself.

**Comment by gdetrez** [comment]
I made a quick fix locally, so that I can use bw with my config, I'll try to add some tests and make it a proper PR.

**Pull request closed without merging**
