### PR TITLE
Add tests to MANIFEST.in

### PR DESCRIPTION
**Pull request by koobs**
Add tests to MANIFEST.in so that they are included in the sdist on PyPI.

This allows users & packagers downstream to QA using release distributions.

### CODE REVIEW

**Comment by ralphbean** [comment]
> This allows users & packagers downstream to QA using release distributions.

:100:

Thanks!

**Comment by ralphbean** [comment]
@koobs, it should be available [on pypi now](https://pypi.python.org/pypi/bugwarrior).

**Comment by koobs** [comment]
Thanks Ralph :) Hope you didn't re-roll the distfile, it will break downstream packages that rely on it and its checksum ;) Quick bump version!

**Comment by koobs** [comment]
I have another change coming, hang on a tick :)

**Pull request merged**
