### PR TITLE
Include an option to disable HTTPS for GitLab.

### PR DESCRIPTION
**Pull request by zackp30**
Not everyone uses HTTPS for GitLab unfortuently.

Hope this is okay.

### CODE REVIEW

**Comment by ralphbean** [comment]
Thanks @zackp30!  Can I ask two things of you?

- Can you add it to the docs/ folder so people know about it?
- Can you make sure it defaults to ``https``?

**Comment by zackp30** [comment]
Sure! I will get around to it soon, currently at work.

**Comment by ralphbean** [comment]
@zackp30 just following up.  This is a good patch!  Any chance you can finish out the docs?

If it's not going to happen, just let me know and I can try to fill them out.

**Comment by mathstuf** [comment]
Might be better to call it `use_https` as a boolean rather than having the value be `https`.

**Comment by zackp30** [comment]
Gah! Sorry I forgot about this, I've been working through GCSEs and school. :frowning:

**Comment by ralphbean** [comment]
All good!  It's taken care of.  Thanks for submitting it @zackp30!

**Pull request merged**
