### PR TITLE
Add support for Pivotal Tracker service

### LINKED ISSUE #409: Pivotal Tracker integration

### PR DESCRIPTION
**Pull request by amdemas**
This resolves #409

### CODE REVIEW

**Comment by ralphbean** [comment]
Well, no response from @bruno- and @hauleth in #409.

@amdemas, are you using this successfully?

If we merge it, are you available for pings to help with tickets if people report bugs on it in the future?

**Comment by amdemas** [comment]
@ralphbean I'll be more than happy to help and maintain it when it's merged in. I am using it, but it has been a bit since I have used some of the other components in the update. I'll ping back once I look it over.

**Comment by JamieSK** [comment]
I'm trying to try this out locally but can't find my user_id on the pivotal website, where are you getting this from?

**Comment by hauleth** [comment]
@JamieSK I do not use PT anymore, but you can find it in your settings IIRC.

**Comment by JamieSK** [comment]
I can only find User Name, not ID, but I might well be being blind

**Comment by amdemas** [comment]
@JamieSK I believe this was a typo on my part. The user_id is your username which can be found under the profile section.

**Comment by JamieSK** [comment]
The code gives me the impression that this value is being converted to an int, whereas my user id is a string

**Comment by amdemas** [comment]
@JamieSK You are correct, and looking at my notes from back then it did seem that Pivotal had a section for the User ID displayed by the username within the profile. It seems that reference has been removed... Let me see what I can do to accommodate this change. My thought is update the docs to explain how to get the user id via the API or just update the code to use the username. However, thinking back I recall pivotal does not enforce a unique username or initials for users, but I could be wrong.

**Comment by JamieSK** [comment]
Great, thanks. I'll do my best to test this once you've got it working

**Comment by amdemas** [comment]
@JamieSK I have updated the docs on how to obtain a user_id https://github.com/ralphbean/bugwarrior/pull/666/commits/c5e023d66ce9162893beb115f461bba04637728a 

Thanks for helping with testing.

**Comment by JamieSK** [comment]
I'm now getting this error on `bugwarrior-pull`:
`INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [pivotaltracker]
Traceback (most recent call last):
  File "/usr/local/bin/bugwarrior-pull", line 11, in <module>
    load_entry_point('bugwarrior==1.7.0', 'console_scripts', 'bugwarrior-pull')()
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/command.py", line 73, in pull
    synchronize(issue_generator, config, main_section, dry_run)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/db.py", line 351, in synchronize
    issue_dict = dict(issue)
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/services/__init__.py", line 413, in keys
    return list(self.__iter__())
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/services/__init__.py", line 408, in __iter__
    record = self.get_taskwarrior_record()
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/services/__init__.py", line 305, in get_taskwarrior_record
    self._taskwarrior_record = self.to_taskwarrior()
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/services/pivotaltracker.py", line 69, in to_taskwarrior
    closed = self.parse_date(self.record.get('accepted_at')).replace(microsecond=0)
AttributeError: 'NoneType' object has no attribute 'replace'
`
Looks like it's depending on an accepted_at field which doesn't exist on the task assigned to me?

**Comment by JamieSK** [comment]
`
if self.record.get('accepted_at'):
            closed = self.parse_date(self.record.get('accepted_at')).replace(microsecond=0)
else:
            closed = False
`
This change at line 69 of pivotaltracker.py seems to fix the problem for my use case and I now have imported tasks

**Comment by amdemas** [comment]
@JamieSK Thanks! I have updated it to check for accepted, modified, and created. Though I don't think the created field is a nullable option. :smile:

**Comment by JamieSK** [comment]
bugwarrior-pull seems to close the tasks I have and then re-add them even when nothing has changed on pivotal, I'm not sure if this is expected though as I've not used bugwarrior for other services

**Comment by JamieSK** [comment]
More recent error on bugwarrior-pull:
`
INFO:bugwarrior.db:Service-defined UDAs exist: you can optionally use the `bugwarrior-uda` command to export a list of UDAs you can add to your taskrc file.
INFO:bugwarrior.services:Starting to aggregate remote issues.
INFO:bugwarrior.services:Spawning 1 workers.
INFO:bugwarrior.services:Working on [pivotaltracker]
INFO:bugwarrior.services:Done with [pivotaltracker] in 1.857313s
INFO:bugwarrior.services:Done aggregating remote issues.
INFO:bugwarrior.db:Adding 1 tasks
INFO:bugwarrior.db:Adding task (bw)Feature#170049
ERROR:bugwarrior.db:Unable to add task: Configuration override rc.uda.pivotal_story_type.type:string
Configuration override rc.uda.pivotal_story_type.label:"Story Type"
Configuration override rc.uda.pivotal_estimate.type:numeric
Configuration override rc.uda.pivotal_estimate.label:"Story Estimate"
Configuration override rc.uda.pivotal_request_users.type:string
Configuration override rc.uda.pivotal_request_users.label:"Story Requesting User"
Configuration override rc.uda.pivotal_current_state.type:string
Configuration override rc.uda.pivotal_current_state.label:"Story State"
Configuration override rc.uda.pivotal_id.type:numeric
Configuration override rc.uda.pivotal_id.label:"Story ID"
Configuration override rc.uda.pivotal_description.type:string
Configuration override rc.uda.pivotal_description.label:"Story Description"
Configuration override rc.uda.pivotal_blockers.type:string
Configuration override rc.uda.pivotal_blockers.label:"Story Blockers"
Configuration override rc.dependency.confirmation:no
Configuration override rc.json.array:TRUE
Configuration override rc.confirmation:no
Configuration override rc.verbose:new-uuid
The expression could not be evaluated.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bugwarrior-1.7.0-py2.7.egg/bugwarrior/db.py", line 422, in synchronize
    new_task = tw.task_add(**issue)
  File "/usr/local/lib/python2.7/dist-packages/taskw-1.2.0-py2.7.egg/taskw/warrior.py", line 683, in task_add
    stdout, stderr = self._execute('add', *args)
  File "/usr/local/lib/python2.7/dist-packages/taskw-1.2.0-py2.7.egg/taskw/warrior.py", line 476, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
TaskwarriorError: ['task', 'rc:/home/jamie/.taskrc', 'rc.uda.pivotal_story_type.type=string', 'rc.uda.pivotal_story_type.label="Story Type"', 'rc.uda.pivotal_estimate.type=numeric', 'rc.uda.pivotal_estimate.label="Story Estimate"', 'rc.uda.pivotal_request_users.type=string', 'rc.uda.pivotal_request_users.label="Story Requesting User"', 'rc.uda.pivotal_current_state.type=string', 'rc.uda.pivotal_current_state.label="Story State"', 'rc.uda.pivotal_id.type=numeric', 'rc.uda.pivotal_id.label="Story ID"', 'rc.uda.pivotal_description.type=string', 'rc.uda.pivotal_description.label="Story Description"', 'rc.uda.pivotal_blockers.type=string', 'rc.uda.pivotal_blockers.label="Story Blockers"', 'rc.dependency.confirmation=no', 'rc.json.array=TRUE', 'rc.confirmation=no', 'rc.verbose=new-uuid', 'add', 'description:""', 'end:', 'entry:"20191202T125426Z"', 'modified:"20191204T161702Z"', 'pivotal_blockers:"[]"', 'pivotal_current_state:"started"', 'pivotal_description:"### Overview"', 'pivotal_estimate:"1"', 'pivotal_id:"170049087"', 'pivotal_request_users:"jk"', 'pivotal_story_type:"feature"', 'priority:"M"', 'project:"Applications"', 'tags:'] #2; stderr:"Configuration override rc.uda.pivotal_story_type.type:string
Configuration override rc.uda.pivotal_story_type.label:"Story Type"
Configuration override rc.uda.pivotal_estimate.type:numeric
Configuration override rc.uda.pivotal_estimate.label:"Story Estimate"
Configuration override rc.uda.pivotal_request_users.type:string
Configuration override rc.uda.pivotal_request_users.label:"Story Requesting User"
Configuration override rc.uda.pivotal_current_state.type:string
Configuration override rc.uda.pivotal_current_state.label:"Story State"
Configuration override rc.uda.pivotal_id.type:numeric
Configuration override rc.uda.pivotal_id.label:"Story ID"
Configuration override rc.uda.pivotal_description.type:string
Configuration override rc.uda.pivotal_description.label:"Story Description"
Configuration override rc.uda.pivotal_blockers.type:string
Configuration override rc.uda.pivotal_blockers.label:"Story Blockers"
Configuration override rc.dependency.confirmation:no
Configuration override rc.json.array:TRUE
Configuration override rc.confirmation:no
Configuration override rc.verbose:new-uuid
The expression could not be evaluated."; stdout:""
INFO:bugwarrior.db:Updating 0 tasks
INFO:bugwarrior.db:Closing 2 tasks

`

I've taken a bit of info out of this but it should still make sense. I think the only things I'd changed is to deliver one of the tasks I'd formerly imported and start the other.

**Comment by amdemas** [comment]
@JamieSK Thanks for the info! I will take a look into what could be causing that and should get something out soon.

**Comment by amdemas** [comment]
@JamieSK I have pushed up some changes to fix some of the issues you may be facing.

**Comment by JamieSK** [comment]
`bugwarrior-pull` still closes any open tasks I have in taskwarrior and the re-adds them if they're still present on pivotal. Is this what you'd expect to happen?

**Comment by amdemas** [comment]
@JamieSK It looks like I have `legacy_matching = True` enabled in my bugwarriorrc config which is why I am not having that issue. I will look to update it to support non-legacy matching.

**Comment by JamieSK** [comment]
I've not set that either way so it'll be whatever is default

**Comment by amdemas** [comment]
@JamieSK Okay, so switching that flag to `False` results in the issue you are having. The latest commit fixes it to support the default setting for matching.

**Comment by JamieSK** [comment]
Seems to be working, nice job, thanks!

**Comment by amdemas** [comment]
No problem, thanks for testing! @ralphbean Everything seems to be in order with it now.

**Review by ryneeverett — APPROVED** [review]

**Pull request merged**
