### PR TITLE
support for python 3.12

### PR DESCRIPTION
**Pull request by NeilHanlon**
python3.12 removed `readfp()`, recommended to use `read_file()` instead

### CODE REVIEW

**Comment by NeilHanlon** [comment]
Note: the if condition is to support python 2.X... not sure if that is necessary.

**Comment by ryneeverett** [comment]
Thanks. We've already dropped support for python-2. Please remove the if-condition (which should fix CI since you forgot to `import sys`) and, if you wouldn't mind, add the later python versions to `.github/workflows/bugwarrior.yml`. Note that the `python-version`s are listed two different places in the file. (I'm sure there's a smarter way to avoid that duplication but :shrug:.)

**Comment by NeilHanlon** [comment]
Absolutely, I can do that.

Would you like me to add all the versions between 3.9 (latest in the github action config) and 3.12, or just append 3.12 to the list?

**Comment by ryneeverett** [comment]
If you could add all the versions from 3.9 through 3.12 that would be great.

**Comment by ryneeverett** [comment]
Looking at the CI failure, it seems that yaml interprets `3.10` as a float and converts it to `3.1`. I think it would be fixed by just putting `"3.10"` in quotes.

**Comment by NeilHanlon** [comment]
thanks for that - apologies that this fell off my radar

**Comment by ryneeverett** [comment]
No problem, it happens. I let this fall off my radar too since the repository owner opened a rival pull request and I wanted to give him a chance to get involved if he was interested.

**Comment by ralphbean** [comment]
Sorry for competing! Thanks for resolving @ryneeverett.

**Pull request merged**
