### PR TITLE
[WIP] Flake8 cleanup

### PR DESCRIPTION
**Pull request by nblock**
- [x] Move flake8 configuration to `.flake8`
- [x] Invoke `flake8` from Travis and Tox
- [ ] Fix all flake8 warnings

How about integrating [Black](https://github.com/python/black)? Python3.6+ is already required in Tox/Travis.

### CODE REVIEW

**Comment by ralphbean** [comment]
Nack!  I'm open to doing some flake8 cleanup, but please do it in small incremental batches that we can merge piece at a time.

It is easier to review - and it is easier to rebase other PRs in the to-merge backlog.

**Comment by ralphbean** [comment]
Eh... nevermind.  Go ahead and finish and we'll just have to deal with the rebase trouble.

Black looks interesting.  I'll play with it and see.  :)

**Comment by ralphbean** [comment]
Any luck here @nblock?

If you're not actively working on this, I'm inclined to close this and just reformat with `black` in the near future.  It will wreck all pending PRs, so I want to resolve as many as possible first.

**Comment by nblock** [comment]
Go with black and don't bother with this at all.

**Pull request closed without merging**
