### PR TITLE
WIP: Client certificate support (#675)

### LINKED ISSUE #675: Client certificate support
It would be great if using client certificates could be used when contacting external services like JIRA.

### PR DESCRIPTION
**Pull request by fdcds**
Adds the `ssl_client_cert`, `ssl_client_key`, `ssl_client_key_password`
and `ssl_client_ca` service parameters to the JIRA service, which allow
to connect to JIRA instances that are secured by SSL client certificates
issued by a private / self-signed CA.

The certificate key file may optionally be encrypted using a password,
which can be retrieved from an `@oracle` like regular passwords.

Closes: #675

WIP: Do not merge, yet.

.plan:
* [ ] Move parts of this into [jira-python](https://github.com/pycontribs/jira), where it probably belongs
  - Actually it should be moved even further down the stack, into [requests](https://github.com/kennethreitz/requests), but that is still blocked by shortcomings of requests:
    - Password protected client certificate keys:
      - kennethreitz/requests#1573
      - kennethreitz/requests#2519
    - Server certificate verification against a custom CA, while using client certificates:
      - kennethreitz/requests#5103
  - Several issues exist regarding this topic in jira-python:
    - pycontribs/jira#311
    - pycontribs/jira#558
    - pycontribs/jira#637
  - A PR exists to fix these issues:
    - pycontribs/jira#838
  - But it will not support password protected keys and a custom CA, since it relies on requests
* [ ] Cleanup
* [ ] Add end-user documentation

### CODE REVIEW

**Comment by ralphbean** [comment]
Any luck with this @fdcds?

**Comment by fdcds** [comment]
> Any luck with this @fdcds?

The next slot for me to work on this will be Thursday night.

**Comment by ryneeverett** [comment]
triage: Any interest in rebasing and completing this?

**Comment by fdcds** [comment]
> triage: Any interest in rebasing and completing this?

No, I do not use bugwarrior anymore.

**Pull request closed without merging**
