### PR TITLE
Allow unlimited description and annotation lengths. Resolve #441.

### LINKED ISSUE #441: Support for unbounded length annotations?
I am *loving* bugwarrior, not least because rather than having to visit 3rd-party tools I can see everything I'm doing right in TaskWarrior. It's seriously made an enormous impact to both my workflow and my enjoyment of getting things done in general. However, I'm having a tricky time finding a clean way to allow unbounded length annotations.

I was hoping that setting `annotation_length = 0` would allow annotations to be of any length; instead it appears to reduce annotations to the shortest length possible, which is the opposite of what I'm after.

Right now I've got `annotation_length` set to a very large number, but that doesn't feel like a very clean way of doing things.

Is there a way to tell bugwarrior to use unbounded length annotations, or if not, may I humbly suggest `annotation_length = 0` be a way of doing this?

### PR DESCRIPTION
**Pull request by ryneeverett**
<s>This is alternative proposal to #436.

The advantage to subclassing ConfigParser rather than using
allow_no_value is that we don't have to worry about handling None for
other value types.</s>

### CODE REVIEW

**Comment by ryneeverett** [comment]
@pjf I was actually just about to close this in favor of #438. I wrote this patch as an alternative to #438 because I thought that approach would require setting `allow_no_value=True`. Well we both just found out that that was a false dilemma.

**Comment by ryneeverett** [comment]
Closing in favor of #438.

**Comment by pjf** [comment]
@ryneeverett : I agree with you here! I think I was just so excited to see *test cases* that I clicked the review button out of sheer joy. :)

**Comment by ryneeverett** [comment]
@pjf Yeah, I really should write tests for this feature.

**Pull request merged**
