### PR TITLE
[WIP] bts: Allow to ignore bugs by tag

### PR DESCRIPTION
**Pull request by irl**
This commit adds the ability to ignore bugs that have been marked as "wontfix". It also adds a new UDA containing the tags on bugs as a side effect.

### CODE REVIEW

**Comment by ryneeverett** [comment]
They're tagged as wontfix but not closed?

**Comment by irl** [comment]
wontfix means that the current maintainer is not interested in fixing the problem. They may still accept a patch if it's well done, or a future maintainer may feel differently about the bug.

**Comment by ryneeverett** [comment]
Ah, that makes sense. However, I wonder if it wouldn't be better to have an option to import bts tags as taskwarrior tags and then another option to ignore arbitrary tags?

**Comment by irl** [comment]
That sounds like a decent idea, I'll take a go at that.

**Comment by ralphbean** [comment]
Hey @irl - we're at the PyCon Sprints and using the time to review the open pull requests here (which I've neglected for too long).  I'm going to close this one since it's been inactive for a while.  Feel free to resubmit if you want to bring it back.

**Pull request closed without merging**
