### PR TITLE
 Add an option to always make the target/section name the project for Phabricator issues/diffs

### PR DESCRIPTION
**Pull request by ghost**
This depends on #561

### CODE REVIEW

**Comment by ryneeverett** [comment]
Needs a rebase and documentation

I'd prefer isolating this feature rather than adding more nested if-statements in the loops. That is, just override the `project` variable at the end of the function:
```py
if self.target_is_project:
    project = self.target
```

Also, is this a feature you actually want? Seems like a strange use case to me.

**Comment by devurandom** [comment]
Initially I thought taking the taskwarrior projects attribute from the Phabricator project tags would work, but it turned out that I'd need a way to prioritise them, in case there is more than one tag. So I came up with having multiple sections for the same `phabricator.host` instead. Each section has a different name and `phabricator.project_phids`, so the result is that my taskwarrior tasks get a deterministic project attribute.

**Comment by ryneeverett** [comment]
Would it be better to use ‘myphabtarget.add_tags=myphabtarget’ and prioritize with tags instead?

**Comment by devurandom** [comment]
`myphabtarget.add_tags=myphabtarget` -- what does that do?

When you say "prioritise with tags" you mean [taskwarrior UDA value weights / coefficients](https://taskwarrior.org/docs/priority.html)? In that case: (So far) I did not use projects to prioritise tasks, but to allow me to filter them efficiently (and have this information immediately visible when skimming through the task list) using the `project` column in taskwarrior. Even if tasks in Phabricator have multiple project tags, usually only one of them is related to an actual project (as in area of responsibility), while the others are just tags, like "user story" or "bug" or relations like "team X/Y/Z".

**Comment by ryneeverett** [comment]
Adding a tag with the same name as the target would allow you to filter by that tag the same way you would if it were the project name.

**Comment by ralphbean** [comment]
WDYT, @urzds?   Are you still using this feature in your personal branch?

**Comment by urzds** [comment]
> WDYT, @urzds? Are you still using this feature in your personal branch?

I am still using this. Thanks for reminding me -- I will need to invest some time in the coming weeks and properly re-design my PRs, incorporating the feedback that I received.

**Comment by ralphbean** [comment]
> I am still using this. Thanks for reminding me -- I will need to invest some time in the coming weeks and properly re-design my PRs, incorporating the feedback that I received.

Thanks.  :)  We'll stand by!

**Comment by ralphbean** [comment]
@ghost has been deleted.  :(

Closing this.

**Pull request closed without merging**
