### PR TITLE
Add `jira.body_length` configuration

### LINKED ISSUE #828: Jira: support `body_length` parameter similar to GitHub's
Just like with GitHub, I'd prefer not to have the contents of Jira issues sync'd into TaskWarrior -- it's huge, runs afoul of encoding bugs in TaskWarrior, and leaks potentially-confidential information (particularly in light of taskd's unencrypted data storage!)

Let's add a `body_length` parameter that is used to limit the length of the description copied in.  Setting this to 0 will effectively prevent descriptions from being included at all.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #828.  I ran into #829 while trying to test this locally, so we'll see if that's an issue in CI as well!

### CODE REVIEW

**Comment by djmitche** [comment]
I don't know why I can't get these tests running locally, so I'm doing the "push-and-pray" debugging process..

**Comment by djmitche** [comment]
Prayer Works? lol

**Comment by ryneeverett** [comment]
> I don't know why I can't get these tests running locally, so I'm doing the "push-and-pray" debugging process..

I opened #831 to address the state of our development environment.

**Review by ryneeverett — APPROVED** [review]
Could we have tests? Seems like a trivial copy/paste from #782.

**Comment by djmitche** [comment]
I can try :)

**Comment by djmitche** [comment]
Using `pytest` instead of push-and-pray helped :)

**Comment by djmitche** [comment]
@ryneeverett is it OK for me to merge this?

**Comment by ryneeverett** [comment]
> @ryneeverett is it OK for me to merge this?

Of course!

**Pull request merged**
