### PR TITLE
Hack to let task-2.4.x search for url UDAs.

### PR DESCRIPTION
**Pull request by ralphbean**
As discussed in ralphbean/taskw#87.

### CODE REVIEW

**Comment by coddingtonbear** [comment]
:+1:

**Comment by coddingtonbear** [comment]
Oh -- as long as we know that'll work for integer PKs, too, of course.

**Comment by ralphbean** [comment]
> Oh -- as long as we know that'll work for integer PKs, too, of course.

Just checked and it works.  :)

**Pull request merged**
