### PR TITLE
Replace remaining urrlib2 usage with requests.

### PR DESCRIPTION
**Pull request by ryneeverett**
Note: I do not have any way to test this out on these services.

### CODE REVIEW

**Comment by ralphbean** [comment]
@umonkey wrote the teamlab integration and @kostajh wrote the activecollab2 stuff.  @umonkey, @kostajh - could you kindly give this a look over?

**Comment by kostajh** [comment]
I (thankfully) haven't had occasion to use ActiveCollab for years, so I can't really give this a meaningful review, sorry @ralphbean!

**Comment by ralphbean** [comment]
@ryneeverett, ok, we waited long enough.  It looks fine to me so I'm :+1: to merge.

**Comment by ryneeverett** [comment]
Yeah, unfortunately this is the best we can do with services we don't use at this point. The solution is more/better tests, but that is my primary motivation behind this PR -- mocking requests is so much easier than urllib2.

**Pull request merged**
