### PR TITLE
(WIP) Adding service support for Gitea

### PR DESCRIPTION
**Pull request by wamsachel**
Mostly just a copy of github.py

Still need to add tests, auth support for tokens, re-write github api strings into gitea

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Do you need some help with this?

**Comment by silascutler** [comment]
Can this be merged in?

**Comment by ryneeverett** [comment]
triage: Has anybody tried this out? Does anybody know why it was labeled WIP and/or what work remains to be done?

**Comment by ryneeverett** [comment]
Closing in favor of #1048.

**Pull request closed without merging**
